# Generated by Django 4.2.3 on 2023-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreedata',
            name='feature1',
            field=models.IntegerField(),
        ),
    ]
