# Generated by Django 4.2.3 on 2023-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_alter_decisiontreedata_feature1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_no', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DecisionTreeData',
        ),
    ]
